"""add competition_images

Revision ID: 075ba0d2c088
Revises: 4d13f5d8ecda
Create Date: 2025-09-30 20:49:26.932152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075ba0d2c088'
down_revision = '4d13f5d8ecda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competition_images')
    # ### end Alembic commands ###
