"""Add active_race_id to global_simulation

Revision ID: add_active_race_id
Revises: 4d13f5d8ecda
Create Date: 2025-01-13 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_active_race_id'
down_revision = '4d13f5d8ecda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_simulation', sa.Column('active_race_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_simulation', 'active_race_id')
    # ### end Alembic commands ###
